[camera.top.calibration]
# The extrinsic rotation for the camera in degrees, xyz euler angles.
extrinsic_rotation = [0.04, -3.001, 1.3]
# The focal length for the camera in pixels.
focal_lengths = [578, 577]
# The optical center of the camera sensor in pixels.
cc_optical_center = [302, 232]

[camera.bottom.calibration]
# The focal length for the camera in pixels.
focal_lengths = [289, 291]
# The optical center of the camera sensor in pixels.
cc_optical_center = [160, 121]
