[package]
name = "tyr_macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "tyr_macros"
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true, features = ["visit-mut", "extra-traits", "derive"] }

[build-dependencies]
rustc_version = { workspace = true }
