# should be in [0, 1]
threshold = 0.55
# for how many detection cycles to listen for a whistle
detection_tries = 8
# how many detections within `detection_tries` detection cycles are required to flag a whistle
detections_needed = 3
