interpolation_type = "Linear"
exit_routine = "Standing"
motion_order = [
    "standup/on_back/ready_to_kick",
    "standup/on_back/kick_up",
    "standup/on_back/half_sit_to_crouch",
    "standup/half_crouch_to_sit",
    "standup/extend_legs",
]
